Huku/create anonymous user
TechCampusDev/gurugurume-api pull request #13
Opened 2024-02-19 12:11 UTC by hukurou0

要約
匿名ユーザを作成し、トークンを発行するAPIとトークンを検証する関数の作成

やったこと
・READMEの更新
・データベース接続できるように
・.envファイルで環境変数を設定できるように
・ファイル構成をMVCに整理
・上記APIと関数の作成

2024-02-19 23:27 UTC, osm-y requested changes
@hukurou0 
コメントしました！確認お願いします 🙏

2024-02-19 23:27 UTC, osm-y commented on README.md
> +基本的に古すぎなければどのバージョンでも問題ないと思われる。version11では動くことを確認済み。
11はEOLを迎えているので、サポート内のバージョンで試した方がいい気もする（他のプロジェクトの関係があれば無理して変える必要はなし）
https://postgresweb.com/post-5471

2024-02-19 23:27 UTC, osm-y commented on README.md
> +docker-compose exec app go run main.go
過去のDockerコンテナ削除して、2~7まで順にやったんですが、ここでこのエラー出ました。
原因わかりますかね？

<img width="607" alt="CleanShot 2024-02-20 at 08 23 07@2x" src="https://github.com/TechCampusDev/gurugurume-api/assets/7239590/0a9bc24a-455a-4476-a379-0ff251c4d075">


DB一覧

<img width="616" alt="CleanShot 2024-02-20 at 08 24 39@2x" src="https://github.com/TechCampusDev/gurugurume-api/assets/7239590/29fb080a-0eb8-4b2c-9b76-15eda3e9e2a2">

2024-02-20 00:39 UTC, hukurou0 commented on README.md
> +基本的に古すぎなければどのバージョンでも問題ないと思われる。version11では動くことを確認済み。
11使ってる開発と14使ってる開発があるので、14だと助かります！14の動作確認してます！

2024-02-20 00:42 UTC, hukurou0 commented on README.md
> +docker-compose exec app go run main.go
以下のコマンドを
```docker-compose exec app go run main.go```
次のコマンドに変更して実行してみてください！
```docker-compose exec app go run .```

理由としては、main.goだけの単一ファイルでなく、複数のファイルを分割コンパイルする必要があるからです。
https://qiita.com/taqm/items/8eed4371bab199b01b65

2024-02-20 00:47 UTC, hukurou0 commented
README更新しました！

2024-02-20 00:58 UTC, osm-y commented
@hukurou0 
ありがとう！できた！
そしたら、4がいらんくて、8と統合できるんじゃない？

修正したらre-requestお願い 🙏 

<img width="583" alt="CleanShot 2024-02-20 at 09 57 31@2x" src="https://github.com/TechCampusDev/gurugurume-api/assets/7239590/d51c9df9-5b4f-4bf6-a98b-4e08e1f71a9f">

2024-02-20 15:09 UTC, hukurou0 commented
@osm-y 
データベース周りで詰まる人が多いかもしれないと思ったので、どこまで完了してるか分かりやすいようにあえて４は残しているのですがどうしましょう？

2024-02-20 15:19 UTC, osm-y commented
なるほど！確かに！じゃあこれでいきましょう 👍

2024-02-20 15:19 UTC, osm-y approved these changes
LGTM!

2024-02-21 02:01 UTC, osm-y commented
@hukurou0 
フクさんの方でマージ&ブランチ削除しちゃってください 👍

2024-02-22 08:47 UTC, hukurou0 commented
@osm-y 
一度やなっちさんのブランチに僕のブランチをマージするので、このpull requestはcloseします！

2024-02-22 08:48 UTC, hukurou0 commented
マージ先をfeature/render-deployに変更するためclose

2024-02-22 08:50 UTC, osm-y commented
基本、正常なものはmainブランチにマージして、その後で最新のmainを別で対応してるブランチに反映させる方がいいよ。
今回やなっちの差分がほぼないからどっちでもいいけど、
> 一度やなっちさんのブランチに僕のブランチをマージするので、このpull requestはcloseします！

の流れにすると、2つのチケットの対応PRがまとまっちゃうので

2024-02-22 08:54 UTC, hukurou0 commented
なるほど！たしかにmainを反映してもらう方が順当な流れですね。ありがとうございます。
一度mainにマージします！

2024-02-22 08:54 UTC, merged